import { EvaluateInstanceTree } from "@rbxts/validate-tree";

export const ServerScriptService = {
	$className: "ServerScriptService",
	server: "Script",
} as const;

export type ServerScriptService = EvaluateInstanceTree<typeof ServerScriptService>;

export const ServerStorage = {
	$className: "ServerStorage",
	Stories: {
		$className: "Folder",
		["main.storybook"]: "ModuleScript",
		Lobby: {
			$className: "Folder",
			LeftSide: {
				$className: "Folder",
				["full.story"]: "ModuleScript",
			},
		},
	},
	__Rojo_SessionLock: "ObjectValue",
} as const;

export type ServerStorage = EvaluateInstanceTree<typeof ServerStorage>;

export const ReplicatedStorage = {
	$className: "ReplicatedStorage",
	assets: {
		$className: "Folder",
		items: {
			$className: "Folder",
			star: {
				$className: "Folder",
				["green star"]: "Model",
				["rainbow star"]: "Model",
				["orange star"]: "Model",
				["purple star"]: {
					$className: "Model",
					Part: {
						$className: "Part",
						Mesh: "SpecialMesh",
						Texture: "Texture",
					},
					Star: "MeshPart",
				},
				["red star"]: "Model",
				["blue star"]: "Model",
			},
		},
		units: {
			$className: "Folder",
			bleach: {
				$className: "Folder",
				aizen: {
					$className: "Folder",
					["1"]: {
						$className: "Folder",
						shiny: {
							$className: "Model",
							["Left Leg"]: {
								$className: "Part",
								["LEG AIZEN.001"]: "Motor6D",
							},
							Humanoid: {
								$className: "Humanoid",
								Animator: "Animator",
							},
							["Right Leg"]: {
								$className: "Part",
								["LEG AIZEN"]: "Motor6D",
							},
							Torso: {
								$className: "Part",
								["Left Shoulder"]: "Motor6D",
								["Right Shoulder"]: "Motor6D",
								Soul: "Motor6D",
								Neck: "Motor6D",
								["Right Hip"]: "Motor6D",
								["TORSO AIZEN"]: "Motor6D",
								["Left Hip"]: "Motor6D",
							},
							HumanoidRootPart: {
								$className: "Part",
								["Root Hip"]: "Motor6D",
							},
							["ARM AIZEN.001"]: "MeshPart",
							["LEG AIZEN"]: "MeshPart",
							["ARM AIZEN"]: "MeshPart",
							HAIR: "MeshPart",
							Head: {
								$className: "Part",
								Mesh: "SpecialMesh",
								["HEAD AIZEN"]: "Motor6D",
							},
							["TORSO AIZEN"]: {
								$className: "MeshPart",
								["WINGS AIZEN"]: "Motor6D",
							},
							Acc: {
								$className: "Folder",
								Soul: {
									$className: "Part",
									PL: "PointLight",
									Att_: {
										$className: "Attachment",
										Wind_Explo: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Ground: "ParticleEmitter",
										Explo: "ParticleEmitter",
									},
									B_: {
										$className: "Attachment",
										Specs: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
									},
									Fire: "ParticleEmitter",
									Att: {
										$className: "Attachment",
										Charge0: "ParticleEmitter",
										Inner_: "ParticleEmitter",
										Fire: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge_: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
							},
							["Right Arm"]: {
								$className: "Part",
								Charge_: "Motor6D",
								["ARM AIZEN"]: "Motor6D",
							},
							["Left Arm"]: {
								$className: "Part",
								Charge: "Motor6D",
								["ARM AIZEN.001"]: "Motor6D",
							},
							["HEAD AIZEN"]: {
								$className: "MeshPart",
								HAIR: "Motor6D",
							},
							["Body Colors"]: "BodyColors",
							["WINGS AIZEN"]: "MeshPart",
							["LEG AIZEN.001"]: "MeshPart",
						},
						model: {
							$className: "Model",
							["Left Leg"]: {
								$className: "Part",
								["LEG AIZEN.001"]: "Motor6D",
							},
							Humanoid: {
								$className: "Humanoid",
								Animator: "Animator",
							},
							["Right Leg"]: {
								$className: "Part",
								["LEG AIZEN"]: "Motor6D",
							},
							Torso: {
								$className: "Part",
								["Left Shoulder"]: "Motor6D",
								["Right Shoulder"]: "Motor6D",
								Soul: "Motor6D",
								Neck: "Motor6D",
								["Right Hip"]: "Motor6D",
								["TORSO AIZEN"]: "Motor6D",
								["Left Hip"]: "Motor6D",
							},
							HumanoidRootPart: {
								$className: "Part",
								["Root Hip"]: "Motor6D",
							},
							["ARM AIZEN.001"]: "MeshPart",
							["LEG AIZEN"]: "MeshPart",
							["ARM AIZEN"]: "MeshPart",
							HAIR: "MeshPart",
							Head: {
								$className: "Part",
								Mesh: "SpecialMesh",
								["HEAD AIZEN"]: "Motor6D",
							},
							["TORSO AIZEN"]: {
								$className: "MeshPart",
								["WINGS AIZEN"]: "Motor6D",
							},
							Acc: {
								$className: "Folder",
								Soul: {
									$className: "Part",
									PL: "PointLight",
									Att_: {
										$className: "Attachment",
										Wind_Explo: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Ground: "ParticleEmitter",
										Explo: "ParticleEmitter",
									},
									B_: {
										$className: "Attachment",
										Specs: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
									},
									Fire: "ParticleEmitter",
									Att: {
										$className: "Attachment",
										Charge0: "ParticleEmitter",
										Inner_: "ParticleEmitter",
										Fire: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge_: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
							},
							["Right Arm"]: {
								$className: "Part",
								Charge_: "Motor6D",
								["ARM AIZEN"]: "Motor6D",
							},
							["Left Arm"]: {
								$className: "Part",
								Charge: "Motor6D",
								["ARM AIZEN.001"]: "Motor6D",
							},
							["HEAD AIZEN"]: {
								$className: "MeshPart",
								HAIR: "Motor6D",
							},
							["Body Colors"]: "BodyColors",
							["WINGS AIZEN"]: "MeshPart",
							["LEG AIZEN.001"]: "MeshPart",
						},
					},
					["0"]: {
						$className: "Folder",
						shiny: {
							$className: "Model",
							["Left Leg"]: {
								$className: "Part",
								["Pants.001"]: "Motor6D",
							},
							Humanoid: {
								$className: "Humanoid",
								Animator: "Animator",
							},
							["Right Leg"]: {
								$className: "Part",
								Pants: "Motor6D",
							},
							["arm sleeves.001"]: "MeshPart",
							Torso: {
								$className: "Part",
								["Left Shoulder"]: "Motor6D",
								["Right Shoulder"]: "Motor6D",
								Soul: "Motor6D",
								Neck: "Motor6D",
								["Right Hip"]: "Motor6D",
								robe: "Motor6D",
								["Left Hip"]: "Motor6D",
							},
							HumanoidRootPart: {
								$className: "Part",
								["Root Hip"]: "Motor6D",
							},
							Shirt: "MeshPart",
							Pants: "MeshPart",
							Head: {
								$className: "Part",
								FKHead: {
									$className: "Part",
									["Aizen Face w Skin Tone Shindo Life"]: "Decal",
									Mesh: "SpecialMesh",
									WeldConstraint: "WeldConstraint",
								},
								glasses: "Motor6D",
								Mesh: "SpecialMesh",
								hair: "Motor6D",
							},
							Acc: {
								$className: "Folder",
								Soul: {
									$className: "Part",
									PL: "PointLight",
									Att_: {
										$className: "Attachment",
										Wind_Explo: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Ground: "ParticleEmitter",
										Explo: "ParticleEmitter",
									},
									B_: {
										$className: "Attachment",
										Specs: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
									},
									Fire: "ParticleEmitter",
									Att: {
										$className: "Attachment",
										Charge0: "ParticleEmitter",
										Inner_: "ParticleEmitter",
										Fire: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge_: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
							},
							["Body Colors"]: "BodyColors",
							belt: "MeshPart",
							["arm sleeves"]: "MeshPart",
							["Right Arm"]: {
								$className: "Part",
								Soul: "Motor6D",
								["arm sleeves"]: "Motor6D",
							},
							["Left Arm"]: {
								$className: "Part",
								["arm sleeves.001"]: "Motor6D",
								Charge: "Motor6D",
							},
							glasses: "MeshPart",
							["Pants.001"]: "MeshPart",
							robe: {
								$className: "MeshPart",
								belt: "Motor6D",
								Shirt: "Motor6D",
							},
							hair: "MeshPart",
						},
						model: {
							$className: "Model",
							["Left Leg"]: {
								$className: "Part",
								["Pants.001"]: "Motor6D",
							},
							Humanoid: {
								$className: "Humanoid",
								Animator: "Animator",
							},
							["Right Leg"]: {
								$className: "Part",
								Pants: "Motor6D",
							},
							["arm sleeves.001"]: "MeshPart",
							Torso: {
								$className: "Part",
								["Left Shoulder"]: "Motor6D",
								["Right Shoulder"]: "Motor6D",
								Soul: "Motor6D",
								Neck: "Motor6D",
								["Right Hip"]: "Motor6D",
								robe: "Motor6D",
								["Left Hip"]: "Motor6D",
							},
							HumanoidRootPart: {
								$className: "Part",
								["Root Hip"]: "Motor6D",
							},
							Shirt: "MeshPart",
							Pants: "MeshPart",
							Head: {
								$className: "Part",
								FKHead: {
									$className: "Part",
									["Aizen Face w Skin Tone Shindo Life"]: "Decal",
									Mesh: "SpecialMesh",
									WeldConstraint: "WeldConstraint",
								},
								glasses: "Motor6D",
								Mesh: "SpecialMesh",
								hair: "Motor6D",
							},
							Acc: {
								$className: "Folder",
								Soul: {
									$className: "Part",
									PL: "PointLight",
									Att_: {
										$className: "Attachment",
										Wind_Explo: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Ground: "ParticleEmitter",
										Explo: "ParticleEmitter",
									},
									B_: {
										$className: "Attachment",
										Specs: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
									},
									Fire: "ParticleEmitter",
									Att: {
										$className: "Attachment",
										Charge0: "ParticleEmitter",
										Inner_: "ParticleEmitter",
										Fire: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
								Charge_: {
									$className: "Part",
									Wind_Explo: "ParticleEmitter",
									Fire: "ParticleEmitter",
									PL: "PointLight",
									Att: {
										$className: "Attachment",
										Shard_Burst_: "ParticleEmitter",
										Explo: "ParticleEmitter",
										Shards2: "ParticleEmitter",
										Wind: "ParticleEmitter",
										Stars: "ParticleEmitter",
										Glow: "ParticleEmitter",
										Shard_Burst: "ParticleEmitter",
										Shock: "ParticleEmitter",
										Fire: "ParticleEmitter",
										Explo_: "ParticleEmitter",
									},
									WeldConstraint: "WeldConstraint",
								},
							},
							["Body Colors"]: "BodyColors",
							belt: "MeshPart",
							["arm sleeves"]: "MeshPart",
							["Right Arm"]: {
								$className: "Part",
								Soul: "Motor6D",
								["arm sleeves"]: "Motor6D",
							},
							["Left Arm"]: {
								$className: "Part",
								["arm sleeves.001"]: "Motor6D",
								Charge: "Motor6D",
							},
							glasses: "MeshPart",
							["Pants.001"]: "MeshPart",
							robe: {
								$className: "MeshPart",
								belt: "Motor6D",
								Shirt: "Motor6D",
							},
							hair: "MeshPart",
						},
					},
				},
			},
		},
	},
	shared: {
		$className: "Folder",
		["interface"]: {
			$className: "Folder",
			leftSideButtons: "ModuleScript",
			constants: {
				$className: "Folder",
				gradients: {
					$className: "ModuleScript",
					blue: "ModuleScript",
					grey: "ModuleScript",
					pink: "ModuleScript",
					rarities: {
						$className: "ModuleScript",
						reborn: "ModuleScript",
						legendary: "ModuleScript",
						secret: "ModuleScript",
						mythical: "ModuleScript",
						epic: "ModuleScript",
						special: "ModuleScript",
						exclusive: "ModuleScript",
						rare: "ModuleScript",
					},
					purple: "ModuleScript",
					silver: "ModuleScript",
					green: "ModuleScript",
					gold: "ModuleScript",
					yellow: "ModuleScript",
					orange: "ModuleScript",
					red: "ModuleScript",
				},
				fonts: {
					$className: "ModuleScript",
					fredokaOne: "ModuleScript",
				},
			},
			types: {
				$className: "ModuleScript",
				misc: "ModuleScript",
				shared: "ModuleScript",
				leftSideButtons: {
					$className: "ModuleScript",
					items: "ModuleScript",
					shop: "ModuleScript",
					profile: "ModuleScript",
					codes: "ModuleScript",
					areas: "ModuleScript",
					trade: "ModuleScript",
					quest: "ModuleScript",
					units: "ModuleScript",
				},
				hotbar: "ModuleScript",
				playerData: {
					$className: "ModuleScript",
					battlepass: "ModuleScript",
					team: "ModuleScript",
					items: "ModuleScript",
					currencies: "ModuleScript",
					level: "ModuleScript",
					statistics: "ModuleScript",
					units: "ModuleScript",
				},
				rightSideButtons: {
					$className: "ModuleScript",
					battlepass: "ModuleScript",
					crates: "ModuleScript",
				},
			},
			components: {
				$className: "Folder",
				iconButton: "ModuleScript",
			},
			utility: {
				$className: "Folder",
				constructors: {
					$className: "Folder",
					makeUnitData: "ModuleScript",
					makeEmptyUnitData: "ModuleScript",
					makeItemPreview: "ModuleScript",
					makeUnitPreview: "ModuleScript",
					makeItemData: "ModuleScript",
				},
				smartGradient: "ModuleScript",
				px: "ModuleScript",
			},
		},
	},
	["tree-definitions"]: "ModuleScript",
	client: {
		$className: "LocalScript",
		interfaceController: {
			$className: "Folder",
			forge: {
				$className: "ModuleScript",
				Track: "ModuleScript",
				Types: "ModuleScript",
			},
			lobby: {
				$className: "Folder",
				leftSideButtons: "ModuleScript",
			},
			props: {
				$className: "ModuleScript",
				rightSideButtons: {
					$className: "ModuleScript",
					battlepass: "ModuleScript",
					crates: "ModuleScript",
				},
				shared: "ModuleScript",
				leftSideButtons: {
					$className: "ModuleScript",
					items: "ModuleScript",
					shop: "ModuleScript",
					profile: "ModuleScript",
					codes: "ModuleScript",
					areas: "ModuleScript",
					trade: "ModuleScript",
					quests: "ModuleScript",
					units: "ModuleScript",
				},
				hotbar: "ModuleScript",
				playerData: {
					$className: "ModuleScript",
					battlepass: "ModuleScript",
					items: "ModuleScript",
					team: "ModuleScript",
					currencies: "ModuleScript",
					level: "ModuleScript",
					statistics: "ModuleScript",
					units: "ModuleScript",
				},
			},
		},
	},
	rbxts_include: {
		$className: "Folder",
		RuntimeLib: "ModuleScript",
		Promise: "ModuleScript",
		node_modules: {
			$className: "Folder",
			["@rbxts"]: {
				$className: "Folder",
				["ui-labs"]: {
					$className: "Folder",
					src: {
						$className: "ModuleScript",
						Controls: {
							$className: "Folder",
							ControlConversion: "ModuleScript",
							PrimitiveControls: "ModuleScript",
							ControlUtils: "ModuleScript",
							Utils: "ModuleScript",
							DatatypeControls: "ModuleScript",
							AdvancedControls: "ModuleScript",
						},
						Utils: "ModuleScript",
						Typing: "Folder",
						ControlTypings: "Folder",
						Version: "ModuleScript",
						Environment: "ModuleScript",
						Libraries: "Folder",
						StoryCreators: "ModuleScript",
						Types: "ModuleScript",
					},
				},
				vide: {
					$className: "Folder",
					src: {
						$className: "ModuleScript",
						defaults: "ModuleScript",
						action: "ModuleScript",
						mount: "ModuleScript",
						changed: "ModuleScript",
						bind: "ModuleScript",
						tags: "ModuleScript",
						jsx: "ModuleScript",
						show: "ModuleScript",
						context: "ModuleScript",
						apply: "ModuleScript",
						untrack: "ModuleScript",
						graph: "ModuleScript",
						maps: "ModuleScript",
						effect: "ModuleScript",
						root: "ModuleScript",
						["switch"]: "ModuleScript",
						derive: "ModuleScript",
						spring: "ModuleScript",
						flags: "ModuleScript",
						read: "ModuleScript",
						source: "ModuleScript",
						["throw"]: "ModuleScript",
						cleanup: "ModuleScript",
						create: "ModuleScript",
						components: "ModuleScript",
						batch: "ModuleScript",
					},
				},
				services: "ModuleScript",
				["validate-tree"]: "ModuleScript",
				["compiler-types"]: {
					$className: "Folder",
					types: "Folder",
				},
				types: {
					$className: "Folder",
					include: {
						$className: "Folder",
						generated: "Folder",
					},
				},
			},
		},
	},
} as const;

export type ReplicatedStorage = EvaluateInstanceTree<typeof ReplicatedStorage>;

export const Lighting = {
	$className: "Lighting",
	ColorGrading: "ColorGradingEffect",
	Bloom: "BloomEffect",
} as const;

export type Lighting = EvaluateInstanceTree<typeof Lighting>;

export const Players = {
	$className: "Players",
	lLonerlDev: {
		$className: "Player",
		PlayerScripts: "PlayerScripts",
		Backpack: "Backpack",
	},
} as const;

export type Players = EvaluateInstanceTree<typeof Players>;

export const Workspace = {
	$className: "Workspace",
	Camera: "Camera",
} as const;

export type Workspace = EvaluateInstanceTree<typeof Workspace>;
